/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sabina
 */
import java.awt.Color;
import java.awt.ComponentOrientation;
import data.User;
import data.Encrypt;

public class LoginPageApp extends javax.swing.JFrame {

    /**
     * Creates new form LoginPageApp
     */
    public LoginPageApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImagineLogin = new javax.swing.JLabel();
        CreateAccountLabel = new java.awt.Label();
        label1 = new java.awt.Label();
        EmailTextBox = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        PasswordTextBox = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MyAccountMenuItem = new javax.swing.JMenu();
        SignUpMenuItem = new javax.swing.JMenu();
        LogInMenuItem = new javax.swing.JMenu();
        MexicanMenuItem = new javax.swing.JMenu();
        GreekMenuItem = new javax.swing.JMenu();
        FrenchMenuItem = new javax.swing.JMenu();
        ItalianMenuItem = new javax.swing.JMenu();
        HomeMenuItem = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(2100, 1200));

        ImagineLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/p2.jpg"))); // NOI18N

        CreateAccountLabel.setBackground(new java.awt.Color(255, 255, 255));
        CreateAccountLabel.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        CreateAccountLabel.setName("CreateAccountLabel"); // NOI18N
        CreateAccountLabel.setText("                     AUTHENTIFICATION");

        label1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        label1.setForeground(new java.awt.Color(85, 26, 139));
        label1.setText("Email");

        EmailTextBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EmailTextBox.setForeground(new java.awt.Color(122, 122, 122));
        EmailTextBox.setText("Email");
        EmailTextBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 26, 139)));
        EmailTextBox.setCaretColor(new java.awt.Color(85, 26, 139));
        EmailTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmailTextBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmailTextBoxMouseExited(evt);
            }
        });
        EmailTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextBoxActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        label2.setForeground(new java.awt.Color(85, 26, 139));
        label2.setText("Password");

        PasswordTextBox.setForeground(new java.awt.Color(122, 122, 122));
        PasswordTextBox.setText("Psssword");
        PasswordTextBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 26, 139)));
        PasswordTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordTextBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PasswordTextBoxMouseExited(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(85, 26, 139));
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Log In");
        LoginButton.setToolTipText("Log In");
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(ImagineLogin)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CreateAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PasswordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(1307, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ImagineLogin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CreateAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(PasswordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(636, Short.MAX_VALUE))
        );

        MenuBar.setBounds(500, 0, 500, 50);
        MenuBar.setBackground(new java.awt.Color(85, 26, 139));
        MenuBar.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        MenuBar.setAlignmentX(-100.0F);
        MenuBar.setAutoscrolls(true);
        MenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuBar.setPreferredSize(new java.awt.Dimension(2200, 80));

        MyAccountMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        MyAccountMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        MyAccountMenuItem.setText("MY ACCOUNT");
        MyAccountMenuItem.setOpaque(true);
        MyAccountMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        MyAccountMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyAccountMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyAccountMenuItemMouseExited(evt);
            }
        });

        SignUpMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        SignUpMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        SignUpMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Account.png"))); // NOI18N
        SignUpMenuItem.setText("Sign Up");
        SignUpMenuItem.setOpaque(true);
        SignUpMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpMenuItemMouseClicked(evt);
            }
        });
        MyAccountMenuItem.add(SignUpMenuItem);

        LogInMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        LogInMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        LogInMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        LogInMenuItem.setText("Log In");
        LogInMenuItem.setOpaque(true);
        LogInMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInMenuItemMouseClicked(evt);
            }
        });
        MyAccountMenuItem.add(LogInMenuItem);

        MenuBar.add(MyAccountMenuItem);

        MexicanMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        MexicanMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        MexicanMenuItem.setText(" MEXICAN KITCHEN");
        MexicanMenuItem.setOpaque(true);
        MexicanMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        MexicanMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(MexicanMenuItem);

        GreekMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        GreekMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        GreekMenuItem.setText("GREEK KITCHEN");
        GreekMenuItem.setOpaque(true);
        GreekMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        GreekMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(GreekMenuItem);

        FrenchMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        FrenchMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        FrenchMenuItem.setText("FRENCH KITCHEN");
        FrenchMenuItem.setOpaque(true);
        FrenchMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        FrenchMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(FrenchMenuItem);

        ItalianMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        ItalianMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        ItalianMenuItem.setText("ITALIAN KITCHEN");
        ItalianMenuItem.setOpaque(true);
        ItalianMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        ItalianMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(ItalianMenuItem);

        HomeMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        HomeMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenuItem.setText("           HOME");
        HomeMenuItem.setOpaque(true);
        HomeMenuItem.setPreferredSize(new java.awt.Dimension(120, 20));
        HomeMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(HomeMenuItem);

        jMenu2.setBackground(new java.awt.Color(85, 26, 139));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Revenue.png"))); // NOI18N
        jMenu2.setOpaque(true);
        jMenu2.setPreferredSize(new java.awt.Dimension(700, 20));
        MenuBar.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(85, 26, 139));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jMenu1.setMaximumSize(new java.awt.Dimension(1100, 32767));
        jMenu1.setOpaque(true);
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 20));
        MenuBar.add(jMenu1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2198, Short.MAX_VALUE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextBoxActionPerformed

    private void EmailTextBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailTextBoxMouseEntered
        // TODO add your handling code here:
        
        EmailTextBox.setBackground(new Color(236, 223, 236));
    }//GEN-LAST:event_EmailTextBoxMouseEntered

    private void EmailTextBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailTextBoxMouseExited
        // TODO add your handling code here:
         EmailTextBox.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_EmailTextBoxMouseExited

    private void PasswordTextBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTextBoxMouseEntered
        // TODO add your handling code here:
        PasswordTextBox.setBackground(new Color(236, 223, 236));
    }//GEN-LAST:event_PasswordTextBoxMouseEntered

    private void PasswordTextBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTextBoxMouseExited
        // TODO add your handling code here:
        PasswordTextBox.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_PasswordTextBoxMouseExited

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
		String email = EmailTextBox.getText();
    	String password = data.Encrypt.generateHash(new String(PasswordTextBox.getPassword()).toString());
		System.out.println(password);
    	
    	System.out.println(email);
    	System.out.println(password);
    	User user = servicii.web.LoginUserServiceApp.getUserID2(email);
    	if((servicii.web.LoginUserServiceApp.postUserStatus2(user, password)).equals("true"))
    	{
    		System.out.println("User logat");
            jLabel1.setVisible(false);
            new HomePageLogged().setVisible(true);
            login.Login.putLoggedUserId(user.getId());
            this.setVisible(false);
            
    		 
    	}
    	else
    	{
    		System.out.println("Parola sau user gresit");
    		jLabel1.setText("Incorrect user or password!");
    		jLabel1.setVisible(true);
    	}
    	
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void MyAccountMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountMenuItemMouseEntered
        // TODO add your handling code here:
        MyAccountMenuItem.setBackground(new Color(255, 255, 255));
        MyAccountMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_MyAccountMenuItemMouseEntered

    private void MyAccountMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountMenuItemMouseExited
        // TODO add your handling code here:
        MyAccountMenuItem.setBackground(new Color(85, 26, 139));
        MyAccountMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_MyAccountMenuItemMouseExited

    private void MexicanMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseEntered
        // TODO add your handling code here:
        MexicanMenuItem.setBackground(new Color(255, 255, 255));
        MexicanMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_MexicanMenuItemMouseEntered

    private void MexicanMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseExited
        // TODO add your handling code here:
        MexicanMenuItem.setBackground(new Color(85, 26, 139));
        MexicanMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_MexicanMenuItemMouseExited

    private void GreekMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseEntered
        // TODO add your handling code here:
        GreekMenuItem.setBackground(new Color(255, 255, 255));
        GreekMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_GreekMenuItemMouseEntered

    private void GreekMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseExited
        // TODO add your handling code here:
        GreekMenuItem.setBackground(new Color(85, 26, 139));
        GreekMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_GreekMenuItemMouseExited

    private void FrenchMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseEntered
        // TODO add your handling code here:
        FrenchMenuItem.setBackground(new Color(255, 255, 255));
        FrenchMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_FrenchMenuItemMouseEntered

    private void FrenchMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseExited
        // TODO add your handling code here:
        FrenchMenuItem.setBackground(new Color(85, 26, 139));
        FrenchMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_FrenchMenuItemMouseExited

    private void ItalianMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseEntered
        // TODO add your handling code here:
        ItalianMenuItem.setBackground(new Color(255, 255, 255));
        ItalianMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_ItalianMenuItemMouseEntered

    private void ItalianMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseExited
        // TODO add your handling code here:
        ItalianMenuItem.setBackground(new Color(85, 26, 139));
        ItalianMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ItalianMenuItemMouseExited

    private void HomeMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseEntered
        // TODO add your handling code here:
        HomeMenuItem.setBackground(new Color(255, 255, 255));
        HomeMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_HomeMenuItemMouseEntered

    private void HomeMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseExited
        // TODO add your handling code here:
        HomeMenuItem.setBackground(new Color(85, 26, 139));
        HomeMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_HomeMenuItemMouseExited

    private void SignUpMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMenuItemMouseClicked
        // TODO add your handling code here:
        new RegisterPageApp().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SignUpMenuItemMouseClicked

    private void LogInMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMenuItemMouseClicked
        // TODO add your handling code here:
        new LoginPageApp().setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_LogInMenuItemMouseClicked

    private void HomeMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseClicked
        // TODO add your handling code here:
        new HomePageApp().setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_HomeMenuItemMouseClicked

    private void GreekMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseClicked
        // TODO add your handling code here:
        new GreekKitchenApp().setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_GreekMenuItemMouseClicked

    private void MexicanMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseClicked
        // TODO add your handling code here:
        new MexicanKitchenApp().setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_MexicanMenuItemMouseClicked

    private void FrenchMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseClicked
        // TODO add your handling code here:
        new FrenchKitchenApp().setVisible(true);
        this.setVisible(false);         
    }//GEN-LAST:event_FrenchMenuItemMouseClicked

    private void ItalianMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseClicked
        // TODO add your handling code here:
        new ItalianKitchenApp().setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_ItalianMenuItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPageApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label CreateAccountLabel;
    private javax.swing.JTextField EmailTextBox;
    private javax.swing.JMenu FrenchMenuItem;
    private javax.swing.JMenu GreekMenuItem;
    private javax.swing.JMenu HomeMenuItem;
    private javax.swing.JLabel ImagineLogin;
    private javax.swing.JMenu ItalianMenuItem;
    private javax.swing.JMenu LogInMenuItem;
    private javax.swing.JButton LoginButton;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MexicanMenuItem;
    private javax.swing.JMenu MyAccountMenuItem;
    private javax.swing.JPasswordField PasswordTextBox;
    private javax.swing.JMenu SignUpMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
