/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sabina
 */

import java.awt.Color;
import java.awt.ComponentOrientation;

import data.User;

public class MyAccountPage extends javax.swing.JFrame {

    /**
     * Creates new form MyAccountPage
     */
    public MyAccountPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        NameTextBox = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        EmailTextBox = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        TelephoneTextBox = new javax.swing.JLabel();
        Address1TextBox = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        Address2TextBox = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MyAccountMenuItem = new javax.swing.JMenu();
        CartMenuItem = new javax.swing.JMenu();
        AccountMenuItem = new javax.swing.JMenu();
        LogOutMenuItem = new javax.swing.JMenu();
        MexicanMenuItem = new javax.swing.JMenu();
        GreekMenuItem = new javax.swing.JMenu();
        FrenchMenuItem = new javax.swing.JMenu();
        ItalianMenuItem = new javax.swing.JMenu();
        HomeMenuItem = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1700, 800));
        jScrollPane1.setWheelScrollingEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1700, 800));

        label1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(85, 26, 139));
        label1.setText("MY ACCOUNT");

        NameTextBox.setBackground(new java.awt.Color(236, 223, 236));
        NameTextBox.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        NameTextBox.setOpaque(true);

        label2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(85, 26, 139));
        label2.setText("Email");

        label3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(85, 26, 139));
        label3.setText("Name");

        EmailTextBox.setBackground(new java.awt.Color(236, 223, 236));
        EmailTextBox.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        EmailTextBox.setOpaque(true);

        label4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(85, 26, 139));
        label4.setText("Telephone");

        TelephoneTextBox.setBackground(new java.awt.Color(236, 223, 236));
        TelephoneTextBox.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        TelephoneTextBox.setOpaque(true);

        Address1TextBox.setBackground(new java.awt.Color(236, 223, 236));
        Address1TextBox.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Address1TextBox.setOpaque(true);

        label5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(85, 26, 139));
        label5.setText("First address");

        label6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(85, 26, 139));
        label6.setText("Second address");

        Address2TextBox.setBackground(new java.awt.Color(236, 223, 236));
        Address2TextBox.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Address2TextBox.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(638, 638, 638)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(702, 702, 702)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(549, 549, 549)
                        .addComponent(EmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelephoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 505, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Address1TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address2TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(378, 378, 378))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Address1TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Address2TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TelephoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        label2.getAccessibleContext().setAccessibleName("Email");

        jScrollPane1.setViewportView(jPanel1);

        MenuBar.setBounds(500, 0, 500, 50);
        MenuBar.setBackground(new java.awt.Color(85, 26, 139));
        MenuBar.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        MenuBar.setAlignmentX(-100.0F);
        MenuBar.setAutoscrolls(true);
        MenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuBar.setPreferredSize(new java.awt.Dimension(700, 80));

        MyAccountMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        MyAccountMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        MyAccountMenuItem.setText("MY ACCOUNT");
        MyAccountMenuItem.setOpaque(true);
        MyAccountMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        MyAccountMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyAccountMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyAccountMenuItemMouseExited(evt);
            }
        });
        MyAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyAccountMenuItemActionPerformed(evt);
            }
        });

        CartMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        CartMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        CartMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ShoppingCartM.png"))); // NOI18N
        CartMenuItem.setText("MY CART");
        CartMenuItem.setOpaque(true);
        CartMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartMenuItemMouseClicked(evt);
            }
            
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CartMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CartMenuItemMouseExited(evt);
            }
        });
        MyAccountMenuItem.add(CartMenuItem);

        AccountMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        AccountMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        AccountMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Account.png"))); // NOI18N
        AccountMenuItem.setText("MY ACCOUNT");
        AccountMenuItem.setFocusable(false);
        AccountMenuItem.setOpaque(true);
        AccountMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMenuItemMouseClicked(evt);
            }
        });
        AccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountMenuItemActionPerformed(evt);
            }
        });
        MyAccountMenuItem.add(AccountMenuItem);

        LogOutMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        LogOutMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        LogOutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        LogOutMenuItem.setText("LOG OUT");
        LogOutMenuItem.setOpaque(true);
        LogOutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMenuItemMouseClicked(evt);
            }
        });
        LogOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuItemActionPerformed(evt);
            }
        });
        MyAccountMenuItem.add(LogOutMenuItem);

        MenuBar.add(MyAccountMenuItem);

        MexicanMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        MexicanMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        MexicanMenuItem.setText("  MEXICAN KITCHEN");
        MexicanMenuItem.setOpaque(true);
        MexicanMenuItem.setPreferredSize(new java.awt.Dimension(120, 20));
        MexicanMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(MexicanMenuItem);

        GreekMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        GreekMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        GreekMenuItem.setText("GREEK KITCHEN");
        GreekMenuItem.setOpaque(true);
        GreekMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        GreekMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(GreekMenuItem);

        FrenchMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        FrenchMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        FrenchMenuItem.setText("FRENCH KITCHEN");
        FrenchMenuItem.setOpaque(true);
        FrenchMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        FrenchMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(FrenchMenuItem);

        ItalianMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        ItalianMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        ItalianMenuItem.setText("ITALIAN KITCHEN");
        ItalianMenuItem.setOpaque(true);
        ItalianMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        ItalianMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(ItalianMenuItem);

        HomeMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        HomeMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenuItem.setText("           HOME");
        HomeMenuItem.setOpaque(true);
        HomeMenuItem.setPreferredSize(new java.awt.Dimension(120, 20));
        HomeMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(HomeMenuItem);

        jMenu2.setBackground(new java.awt.Color(85, 26, 139));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Revenue.png"))); // NOI18N
        jMenu2.setOpaque(true);
        jMenu2.setPreferredSize(new java.awt.Dimension(700, 20));
        MenuBar.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(85, 26, 139));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jMenu1.setMaximumSize(new java.awt.Dimension(1100, 32767));
        jMenu1.setOpaque(true);
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 20));
        MenuBar.add(jMenu1);

        setJMenuBar(MenuBar);
        
    	int UserId = login.Login.getLoggedUserId(); 
    	User user = servicii.web.LoginUserServiceApp.getUserID3(UserId);
    	NameTextBox.setText("    " + user.getName());
    	EmailTextBox.setText("   " + user.getEmail());
    	TelephoneTextBox.setText("   " + user.getTelephone());
    	Address1TextBox.setText("   " + user.getAddress1());
    	if(user.getAddress2() != null)
    	{
    		Address2TextBox.setText("   " + user.getAddress2());
    	}
    	else
    	{
    		Address2TextBox.setText("");    		
    	}

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CartMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMenuItemMouseEntered
        // TODO add your handling code here:
        AccountMenuItem.setBackground(new Color(255, 255, 255));
        AccountMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_CartMenuItemMouseEntered

    private void CartMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMenuItemMouseExited
        // TODO add your handling code here:
        AccountMenuItem.setBackground(new Color(85, 26, 139));
        AccountMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_CartMenuItemMouseExited

    private void AccountMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMenuItemMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_AccountMenuItemMouseClicked

    private void AccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountMenuItemActionPerformed

    private void LogOutMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMenuItemMouseClicked
        // TODO add your handling code here:
        new LoginPageApp().setVisible(true);
        login.Login.putLoggedUserId(-1);
        login.Login.clearCart();
        this.setVisible(false);
    }//GEN-LAST:event_LogOutMenuItemMouseClicked

    private void LogOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutMenuItemActionPerformed

    private void MyAccountMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountMenuItemMouseEntered
        // TODO add your handling code here:
        MyAccountMenuItem.setBackground(new Color(255, 255, 255));
        MyAccountMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_MyAccountMenuItemMouseEntered

    private void MyAccountMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountMenuItemMouseExited
        // TODO add your handling code here:
        MyAccountMenuItem.setBackground(new Color(85, 26, 139));
        MyAccountMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_MyAccountMenuItemMouseExited

    private void MyAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyAccountMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyAccountMenuItemActionPerformed

    private void MexicanMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseClicked
        // TODO add your handling code here:
        new MexicanKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MexicanMenuItemMouseClicked

    private void MexicanMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseEntered
        // TODO add your handling code here:
        MexicanMenuItem.setBackground(new Color(255, 255, 255));
        MexicanMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_MexicanMenuItemMouseEntered

    private void MexicanMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseExited
        // TODO add your handling code here:
        MexicanMenuItem.setBackground(new Color(85, 26, 139));
        MexicanMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_MexicanMenuItemMouseExited

    private void GreekMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseClicked
        // TODO add your handling code here:
        new GreekKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GreekMenuItemMouseClicked

    private void GreekMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseEntered
        // TODO add your handling code here:
        GreekMenuItem.setBackground(new Color(255, 255, 255));
        GreekMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_GreekMenuItemMouseEntered

    private void GreekMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseExited
        // TODO add your handling code here:
        GreekMenuItem.setBackground(new Color(85, 26, 139));
        GreekMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_GreekMenuItemMouseExited

    private void FrenchMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseClicked
        // TODO add your handling code here:
        new FrenchKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FrenchMenuItemMouseClicked

    private void FrenchMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseEntered
        // TODO add your handling code here:
        FrenchMenuItem.setBackground(new Color(255, 255, 255));
        FrenchMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_FrenchMenuItemMouseEntered

    private void FrenchMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseExited
        // TODO add your handling code here:
        FrenchMenuItem.setBackground(new Color(85, 26, 139));
        FrenchMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_FrenchMenuItemMouseExited

    private void ItalianMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseClicked
        // TODO add your handling code here:
        new ItalianKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ItalianMenuItemMouseClicked

    private void ItalianMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseEntered
        // TODO add your handling code here:
        ItalianMenuItem.setBackground(new Color(255, 255, 255));
        ItalianMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_ItalianMenuItemMouseEntered

    private void ItalianMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseExited
        // TODO add your handling code here:
        ItalianMenuItem.setBackground(new Color(85, 26, 139));
        ItalianMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ItalianMenuItemMouseExited

    private void HomeMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseClicked
        // TODO add your handling code here:
        new HomePageLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMenuItemMouseClicked

    private void HomeMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseEntered
        // TODO add your handling code here:
        HomeMenuItem.setBackground(new Color(255, 255, 255));
        HomeMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_HomeMenuItemMouseEntered

    private void HomeMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseExited
        // TODO add your handling code here:
        HomeMenuItem.setBackground(new Color(85, 26, 139));
        HomeMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_HomeMenuItemMouseExited
    
    private void CartMenuItemMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    }  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccountPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AccountMenuItem;
    private javax.swing.JLabel Address1TextBox;
    private javax.swing.JLabel Address2TextBox;
    private javax.swing.JMenu CartMenuItem;
    private javax.swing.JLabel EmailTextBox;
    private javax.swing.JMenu FrenchMenuItem;
    private javax.swing.JMenu GreekMenuItem;
    private javax.swing.JMenu HomeMenuItem;
    private javax.swing.JMenu ItalianMenuItem;
    private javax.swing.JMenu LogOutMenuItem;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MexicanMenuItem;
    private javax.swing.JMenu MyAccountMenuItem;
    private javax.swing.JLabel NameTextBox;
    private javax.swing.JLabel TelephoneTextBox;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables
}
