/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sabina
 */

import java.awt.Button;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Label;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;

import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriBuilder;

import org.glassfish.jersey.client.ClientConfig;
import org.glassfish.jersey.client.HttpUrlConnectorProvider;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;

import data.Cart;
import data.OrderProduct;
import data.OrderUser;
import data.Product;
import data.User;



public class MyCartPage extends javax.swing.JFrame {
	
	private static URI getBaseURI() {
		//TODO change the port to whatever is the server running on
		return UriBuilder.fromUri("http://localhost:8081/SSW/").build();
	}
	
	 /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	class NameActionListener implements ActionListener {
	    private String name;

	    public NameActionListener(String name) {
	        this.name = name;
	    }

	    public void actionPerformed(ActionEvent e) {
	    	
	    	
	        RemoveFromCart(name);
	    }
	}

    /**
     * Creates new form MyCartPage
     */
    public MyCartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	int nrOfProdInCart = login.Login.MyCart.size();   	
    	System.out.println(nrOfProdInCart);
    	
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jButton12 = new javax.swing.JButton();

        MenuBar = new javax.swing.JMenuBar();
        MyAccountMenuItem = new javax.swing.JMenu();
        CartMenuItem = new javax.swing.JMenu();
        AccountMenuItem = new javax.swing.JMenu();
        LogOutMenuItem = new javax.swing.JMenu();
        MexicanMenuItem = new javax.swing.JMenu();
        GreekMenuItem = new javax.swing.JMenu();
        FrenchMenuItem = new javax.swing.JMenu();
        ItalianMenuItem = new javax.swing.JMenu();
        HomeMenuItem = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1600, 900));
        
        
        jScrollPane1.setWheelScrollingEnabled(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 3000));
        jPanel1.setLayout(null);

        label1 = new Label();
        label1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(85, 26, 139));
        label1.setBounds(0, 0, 150, 30);
        label1.setText("MY CART");
        label1.setLocation(new Point(700, 100));
        jPanel1.add(label1);
        jPanel1.validate();
        jPanel1.repaint();

        ArrayList<Button> buttons = new ArrayList<>();
    	int offset = 0;
        
        if(nrOfProdInCart==0)
        {
        	Label label = new Label();
        	
            label.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
            label.setForeground(new java.awt.Color(85, 26, 139));
            label.setBounds(0, 0, 300, 30);
            label.setText("Your cart is empty!");
            label.setLocation(new Point(650, 200));
            jPanel1.add(label);
            jPanel1.validate();
            jPanel1.repaint();
        }
        else
        {
        	
        	for(Product key: login.Login.MyCart.keySet())
        	{
        		int freq = login.Login.MyCart.get(key);
        		double price = key.getPrice();
        		String name = key.getName();
        		
                Button b = new Button(); 
                b.setBackground(new java.awt.Color(236, 223, 236));
                b.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
                b.setBounds(0, 0, 30, 30);
                b.setLabel("X");
                b.setLocation(600, 200+offset);
                b.addActionListener(new NameActionListener(name));
                buttons.add(b);
                
                
                jPanel1.add(b);
                jPanel1.validate();
                jPanel1.repaint();
                
            	Label label = new Label();
            	
                label.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
                label.setForeground(new java.awt.Color(85, 26, 139));
                label.setBounds(0, 0, 300, 30);
                if(freq == 1)
                	label.setText(name + " - " + price + "$");
                else
                	label.setText(freq + " X " + name + " - " + Math.floor(price*freq * 100) / 100 + "$");
                label.setLocation(new Point(650, 200+offset));
                jPanel1.add(label);
                jPanel1.validate();
                jPanel1.repaint();
                offset+=50;
                
                
        	}
        }
        
        P12 = new Label();
        P12.setForeground(new java.awt.Color(85, 26, 139));
        P12.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        P12.setText("Total cost : " +  login.Login.getTotalPrice() + "$");
        P12.setBounds(0, 0, 300, 30);
        P12.setLocation(new Point(650, 250+offset));        
        jPanel1.add(P12);
        jPanel1.validate();
        jPanel1.repaint();
        
        Button commandButton = new Button(); 
        commandButton.setBackground(new java.awt.Color(236, 223, 236));
        commandButton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        commandButton.setBounds(0, 0, 100, 30);
        commandButton.setLabel("Command");
        commandButton.setLocation(700, 350+offset);
        commandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	commandButtonActionEvent(evt);
            }
        });
        
        jPanel1.add(commandButton);
        jPanel1.validate();
        jPanel1.repaint();
      
        jScrollPane1.setViewportView(jPanel1);

        MenuBar.setBounds(500, 0, 500, 50);
        MenuBar.setBackground(new java.awt.Color(85, 26, 139));
        MenuBar.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        MenuBar.setAlignmentX(-100.0F);
        MenuBar.setAutoscrolls(true);
        MenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuBar.setPreferredSize(new java.awt.Dimension(700, 80));

        MyAccountMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        MyAccountMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        MyAccountMenuItem.setText("MY ACCOUNT");
        MyAccountMenuItem.setOpaque(true);
        MyAccountMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        MyAccountMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyAccountMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyAccountMenuItemMouseExited(evt);
            }
        });
        MyAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyAccountMenuItemActionPerformed(evt);
            }
        });

        CartMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        CartMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        CartMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ShoppingCartM.png"))); // NOI18N
        CartMenuItem.setText("MY CART");
        CartMenuItem.setOpaque(true);
        CartMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartMenuItemMouseClicked(evt);
            }
  
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CartMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CartMenuItemMouseExited(evt);
            }
        });
        MyAccountMenuItem.add(CartMenuItem);

        AccountMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        AccountMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        AccountMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Account.png"))); // NOI18N
        AccountMenuItem.setText("MY ACCOUNT");
        AccountMenuItem.setFocusable(false);
        AccountMenuItem.setOpaque(true);
        AccountMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMenuItemMouseClicked(evt);
            }
        });
        AccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountMenuItemActionPerformed(evt);
            }
        });
        MyAccountMenuItem.add(AccountMenuItem);

        LogOutMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        LogOutMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        LogOutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        LogOutMenuItem.setText("LOG OUT");
        LogOutMenuItem.setOpaque(true);
        LogOutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMenuItemMouseClicked(evt);
            }
        });
        LogOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuItemActionPerformed(evt);
            }
        });
        MyAccountMenuItem.add(LogOutMenuItem);

        MenuBar.add(MyAccountMenuItem);

        MexicanMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        MexicanMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        MexicanMenuItem.setText("  MEXICAN KITCHEN");
        MexicanMenuItem.setOpaque(true);
        MexicanMenuItem.setPreferredSize(new java.awt.Dimension(120, 20));
        MexicanMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(MexicanMenuItem);

        GreekMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        GreekMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        GreekMenuItem.setText("GREEK KITCHEN");
        GreekMenuItem.setOpaque(true);
        GreekMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        GreekMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(GreekMenuItem);

        FrenchMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        FrenchMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        FrenchMenuItem.setText("FRENCH KITCHEN");
        FrenchMenuItem.setOpaque(true);
        FrenchMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        FrenchMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(FrenchMenuItem);

        ItalianMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        ItalianMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        ItalianMenuItem.setText("ITALIAN KITCHEN");
        ItalianMenuItem.setOpaque(true);
        ItalianMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        ItalianMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(ItalianMenuItem);

        HomeMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        HomeMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenuItem.setText("           HOME");
        HomeMenuItem.setOpaque(true);
        HomeMenuItem.setPreferredSize(new java.awt.Dimension(120, 20));
        HomeMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(HomeMenuItem);

        jMenu2.setBackground(new java.awt.Color(85, 26, 139));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Revenue.png"))); // NOI18N
        jMenu2.setOpaque(true);
        jMenu2.setPreferredSize(new java.awt.Dimension(700, 20));
        MenuBar.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(85, 26, 139));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jMenu1.setMaximumSize(new java.awt.Dimension(1100, 32767));
        jMenu1.setOpaque(true);
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 20));
        MenuBar.add(jMenu1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    protected void bButtonActionEvent(ActionEvent evt) {
		// TODO Auto-generated method stub
		
	}

	private void CartMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMenuItemMouseEntered
        // TODO add your handling code here:
		CartMenuItem.setBackground(new Color(255, 255, 255));
		CartMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_CartMenuItemMouseEntered

    private void CartMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMenuItemMouseExited
        // TODO add your handling code here:
    	CartMenuItem.setBackground(new Color(85, 26, 139));
    	CartMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_CartMenuItemMouseExited

    private void AccountMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMenuItemMouseClicked
        // TODO add your handling code here:
    	new MyAccountPage().setVisible(true);
    	this.setVisible(false);
    	
    	
    }//GEN-LAST:event_AccountMenuItemMouseClicked

    private void AccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountMenuItemActionPerformed

    private void LogOutMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMenuItemMouseClicked
        // TODO add your handling code here:
        new LoginPageApp().setVisible(true);
        login.Login.setUserID(-1);
        login.Login.clearCart();
        this.setVisible(false);
    }//GEN-LAST:event_LogOutMenuItemMouseClicked

    private void LogOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutMenuItemActionPerformed

    private void MyAccountMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountMenuItemMouseEntered
        // TODO add your handling code here:
        MyAccountMenuItem.setBackground(new Color(255, 255, 255));
        MyAccountMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_MyAccountMenuItemMouseEntered

    private void MyAccountMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountMenuItemMouseExited
        // TODO add your handling code here:
        MyAccountMenuItem.setBackground(new Color(85, 26, 139));
        MyAccountMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_MyAccountMenuItemMouseExited

    private void MyAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyAccountMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyAccountMenuItemActionPerformed

    private void MexicanMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseClicked
        // TODO add your handling code here:
        new MexicanKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MexicanMenuItemMouseClicked

    private void MexicanMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseEntered
        // TODO add your handling code here:
        MexicanMenuItem.setBackground(new Color(255, 255, 255));
        MexicanMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_MexicanMenuItemMouseEntered

    private void MexicanMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseExited
        // TODO add your handling code here:
        MexicanMenuItem.setBackground(new Color(85, 26, 139));
        MexicanMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_MexicanMenuItemMouseExited

    private void GreekMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseClicked
        // TODO add your handling code here:
        new GreekKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GreekMenuItemMouseClicked

    private void GreekMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseEntered
        // TODO add your handling code here:
        GreekMenuItem.setBackground(new Color(255, 255, 255));
        GreekMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_GreekMenuItemMouseEntered

    private void GreekMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseExited
        // TODO add your handling code here:
        GreekMenuItem.setBackground(new Color(85, 26, 139));
        GreekMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_GreekMenuItemMouseExited

    private void FrenchMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseClicked
        // TODO add your handling code here:
        new FrenchKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FrenchMenuItemMouseClicked

    private void FrenchMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseEntered
        // TODO add your handling code here:
        FrenchMenuItem.setBackground(new Color(255, 255, 255));
        FrenchMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_FrenchMenuItemMouseEntered

    private void FrenchMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseExited
        // TODO add your handling code here:
        FrenchMenuItem.setBackground(new Color(85, 26, 139));
        FrenchMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_FrenchMenuItemMouseExited

    private void ItalianMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseClicked
        // TODO add your handling code here:
        new ItalianKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ItalianMenuItemMouseClicked

    private void ItalianMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseEntered
        // TODO add your handling code here:
        ItalianMenuItem.setBackground(new Color(255, 255, 255));
        ItalianMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_ItalianMenuItemMouseEntered

    private void ItalianMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseExited
        // TODO add your handling code here:
        ItalianMenuItem.setBackground(new Color(85, 26, 139));
        ItalianMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ItalianMenuItemMouseExited

    private void HomeMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseClicked
        // TODO add your handling code here:
        new HomePageLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMenuItemMouseClicked

    private void HomeMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseEntered
        // TODO add your handling code here:
        HomeMenuItem.setBackground(new Color(255, 255, 255));
        HomeMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_HomeMenuItemMouseEntered

    private void HomeMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseExited
        // TODO add your handling code here:
        HomeMenuItem.setBackground(new Color(85, 26, 139));
        HomeMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_HomeMenuItemMouseExited
    
    private void CartMenuItemMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    } 
    

	private void commandButtonActionEvent(ActionEvent evt) {
		// TODO Auto-generated method stub
		if(login.Login.MyCart.size()>0)
		{
			String email = login.Login.getEmail();
			User user = new User();
			user.setEmail(email);
			
			OrderUser order = new OrderUser();
			order.setUser(user);
    		Cart cart = new Cart();
    		
			for(Product key: (login.Login.MyCart).keySet())
        	{
        		int quantity = login.Login.MyCart.get(key);
        		for(int i = 0; i < quantity; i++)
        		{
        			cart.AddProduct(key);
        		}
        		
        	}
			order.setCart(cart);
			
			com.fasterxml.jackson.databind.ObjectWriter ow = new ObjectMapper().writer().withDefaultPrettyPrinter();
			String data="";
			try {
				data = ow.writeValueAsString(order);
			} catch (JsonProcessingException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			System.out.println("My string object:" + data);

			ClientConfig config = new ClientConfig();
	        Client client = ClientBuilder.newClient(config);
	      
	        client.property(HttpUrlConnectorProvider.SET_METHOD_WORKAROUND, true);
			WebTarget service = client.target(getBaseURI());
			Response response;

			response = service.path("rest").path("addOrder").request(MediaType.TEXT_PLAIN).post(Entity.entity(data, MediaType.APPLICATION_JSON), Response.class);
			
			System.out.println(response.getStatus());
			System.out.println(response);
			
			if(response.getStatus() == 200) {
				String data2 = response.readEntity(String.class);
				if(data2.equals("true")) {
					System.out.println("Your order was put in place! Thank you for choosing us!");
				}else {
					System.out.println("Your order !");	
				}
				
			}
			else {
				System.out.println("Something went wrong! Windows type of error XD");
			}
			
			
			 login.Login.clearCart();
			 new CommandPage().setVisible(true);
			 
		}
	}
	
	public void RemoveFromCart(String name)
	{
		login.Login.removeFromCart(name);
		new MyCartPage().setVisible(true);
		this.setVisible(false);

	}

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCartPage().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AccountMenuItem;
    private javax.swing.JMenu CartMenuItem;
    private javax.swing.JMenu FrenchMenuItem;
    private javax.swing.JMenu GreekMenuItem;
    private javax.swing.JMenu HomeMenuItem;
    private javax.swing.JMenu ItalianMenuItem;
    private javax.swing.JMenu LogOutMenuItem;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MexicanMenuItem;
    private javax.swing.JMenu MyAccountMenuItem;
    
    private java.awt.Label P12;
    private javax.swing.JButton jButton12;

    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
