/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sabina
 */

import java.awt.Color;
import java.awt.ComponentOrientation;
import javax.swing.JLabel;

public class MyCartPage extends javax.swing.JFrame {

    /**
     * Creates new form MyCartPage
     */
    public MyCartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	int nrOfProdInCart = login.Login.MyCart.size();   	
    	System.out.println(nrOfProdInCart);
    	for(int i = 1; i <= nrOfProdInCart; i++)
    	{
    		
    		System.out.println(login.Login.MyCart.get(i-1).getName());
    	}
    	
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        P1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        P2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        P3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        P4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        P5 = new javax.swing.JLabel();
        P6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        P7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        P8 = new javax.swing.JLabel();
        P9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        P10 = new javax.swing.JLabel();
        P11 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        P12 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MyAccountMenuItem = new javax.swing.JMenu();
        CartMenuItem = new javax.swing.JMenu();
        AccountMenuItem = new javax.swing.JMenu();
        LogOutMenuItem = new javax.swing.JMenu();
        MexicanMenuItem = new javax.swing.JMenu();
        GreekMenuItem = new javax.swing.JMenu();
        FrenchMenuItem = new javax.swing.JMenu();
        ItalianMenuItem = new javax.swing.JMenu();
        HomeMenuItem = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1700, 800));
        jScrollPane1.setWheelScrollingEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1700, 800));

        label1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(85, 26, 139));
        label1.setText("MY CART");

        P1.setBackground(new java.awt.Color(236, 223, 236));
        P1.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        P1.setOpaque(true);
        P1.setPreferredSize(new java.awt.Dimension(341, 24));
        P1.setRequestFocusEnabled(false);
        
        if(nrOfProdInCart>=1)
        {
        	P1.setVisible(true);
        	P1.setText(login.Login.MyCart.get(0).getName() + "   -   "  + login.Login.MyCart.get(0).getPrice()+"$");

        }
        else
        {
        	P1.setVisible(true);
        	P1.setBackground(Color.WHITE);
        	P1.setForeground(new java.awt.Color(85, 26, 139));
        	P1.setText("               Your cart is empty!");
        	P1.setFont(new java.awt.Font("Times New Roman", 3, 24));
        	jButton1.setVisible(false);
        }
        	
        
        
        jButton1.setBackground(new java.awt.Color(236, 223, 236));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(236, 223, 236));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        P2.setBackground(new java.awt.Color(236, 223, 236));
        P2.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        P2.setOpaque(true);
        P2.setPreferredSize(new java.awt.Dimension(341, 24));
        P2.setRequestFocusEnabled(false);
        if(nrOfProdInCart>=2)
        {
        	P2.setVisible(true);
        	P2.setText(login.Login.MyCart.get(1).getName() + "   -   "  + login.Login.MyCart.get(1).getPrice()+"$");
        }
        else
        {
        	P2.setVisible(false);
        	jButton2.setVisible(false);
        }

        jButton3.setBackground(new java.awt.Color(236, 223, 236));
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        P3.setBackground(new java.awt.Color(236, 223, 236));
        P3.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        if(nrOfProdInCart>=3)
        {
            P3.setText(login.Login.MyCart.get(2).getName() +  "   -   "  + login.Login.MyCart.get(2).getPrice()+"$");
        	P3.setVisible(true);
        }
        else
       	{
        	jButton3.setVisible(false);
        	P3.setVisible(false);
        }
        P3.setOpaque(true);
        P3.setPreferredSize(new java.awt.Dimension(341, 24));
        P3.setRequestFocusEnabled(false);

        jButton4.setBackground(new java.awt.Color(236, 223, 236));
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        P4.setBackground(new java.awt.Color(236, 223, 236));
        P4.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        P4.setOpaque(true);
        P4.setPreferredSize(new java.awt.Dimension(341, 24));
        P4.setRequestFocusEnabled(false);
        
        if(nrOfProdInCart>=4)
        {
            P4.setText(login.Login.MyCart.get(3).getName()+ "   -   "  + login.Login.MyCart.get(3).getPrice()+"$");
        	P4.setVisible(true);
        }
        else
       	{
        	jButton4.setVisible(false);
        	P4.setVisible(false);
        }
        
        
        jButton5.setBackground(new java.awt.Color(236, 223, 236));
        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        P5.setBackground(new java.awt.Color(236, 223, 236));
        P5.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        P5.setOpaque(true);
        P5.setPreferredSize(new java.awt.Dimension(341, 24));
        P5.setRequestFocusEnabled(false);
        if(nrOfProdInCart>=5)
        {
            P5.setText(login.Login.MyCart.get(4).getName()+ "   -   "  + login.Login.MyCart.get(4).getPrice()+"$");
        	P5.setVisible(true);
        }
        else
        {
        	jButton5.setVisible(false);
        	P5.setVisible(false);
        }
        
        P6.setBackground(new java.awt.Color(236, 223, 236));
        P6.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        P6.setOpaque(true);
        P6.setPreferredSize(new java.awt.Dimension(341, 24));
        P6.setRequestFocusEnabled(false);
        
        if(nrOfProdInCart>=6)
       	{
            P6.setText(login.Login.MyCart.get(5).getName()+ "   -   "  + login.Login.MyCart.get(5).getPrice()+"$");        	
        	P6.setVisible(true);
        }
        else
        {
        	jButton6.setVisible(false);
        	P6.setVisible(false);
        }


        jButton6.setBackground(new java.awt.Color(236, 223, 236));
        jButton6.setText("X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(236, 223, 236));
        jButton7.setText("X");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        P7.setBackground(new java.awt.Color(236, 223, 236));
        P7.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        if(nrOfProdInCart>=7)
        {
            P7.setText(login.Login.MyCart.get(6).getName()+ "   -   "  + login.Login.MyCart.get(6).getPrice()+"$");          		
        	P7.setVisible(true);
        }
        else
        {
        	jButton7.setVisible(false);
        	P7.setVisible(false);
        }
        P7.setOpaque(true);
        P7.setPreferredSize(new java.awt.Dimension(341, 24));
        P7.setRequestFocusEnabled(false);

        jButton8.setBackground(new java.awt.Color(236, 223, 236));
        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        P8.setBackground(new java.awt.Color(236, 223, 236));
        P8.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        if(nrOfProdInCart>=8)
        {
            P8.setText(login.Login.MyCart.get(7).getName()+ "   -   "  + login.Login.MyCart.get(7).getPrice()+"$");     
        	P8.setVisible(true);
        }
        else
        {
        	jButton8.setVisible(false);
        	P8.setVisible(false);
        }
        P8.setOpaque(true);
        P8.setPreferredSize(new java.awt.Dimension(341, 24));
        P8.setRequestFocusEnabled(false);

        P9.setBackground(new java.awt.Color(236, 223, 236));
        P9.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        if(nrOfProdInCart>=9)
        {
            P9.setText(login.Login.MyCart.get(8).getName()+ "   -   "  + login.Login.MyCart.get(8).getPrice()+"$");  
        	P9.setVisible(true);
        }
        else
        {
        	jButton9.setVisible(false);        	
        	P9.setVisible(false);
        }
        P9.setOpaque(true);
        P9.setPreferredSize(new java.awt.Dimension(341, 24));
        P9.setRequestFocusEnabled(false);

        jButton9.setBackground(new java.awt.Color(236, 223, 236));
        jButton9.setText("X");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(236, 223, 236));
        jButton10.setText("X");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        P10.setBackground(new java.awt.Color(236, 223, 236));
        P10.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        if(nrOfProdInCart>=10)
        {
            P10.setText(login.Login.MyCart.get(9).getName()+ "   -   "  + login.Login.MyCart.get(9).getPrice()+"$");  
        	P10.setVisible(true);
        }
        else
        {
        	jButton10.setVisible(false);
        	P10.setVisible(false);
        }
        P10.setOpaque(true);
        P10.setPreferredSize(new java.awt.Dimension(341, 24));
        P10.setRequestFocusEnabled(false);

        P11.setBackground(new java.awt.Color(236, 223, 236));
        P11.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        if(nrOfProdInCart>=11)
        {
            P11.setText(login.Login.MyCart.get(10).getName() + "   -   " + login.Login.MyCart.get(10).getPrice()+"$");          	
        	P11.setVisible(true);
        }
        else
        {
        	jButton11.setVisible(false);
        	P11.setVisible(false);
        }
        P11.setOpaque(true);
        P11.setPreferredSize(new java.awt.Dimension(341, 24));
        P11.setRequestFocusEnabled(false);

        jButton11.setBackground(new java.awt.Color(236, 223, 236));
        jButton11.setText("X");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });


        jButton12.setBackground(new java.awt.Color(236, 223, 236));
        jButton12.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton12.setText("Command");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        
        P12.setBackground(new java.awt.Color(255, 255, 255));
        P12.setForeground(new java.awt.Color(85, 26, 139));
        P12.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        P12.setText("Total cost : " +  login.Login.getTotalPrice() + "$");
        P12.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        P12.setOpaque(true);
        P12.setPreferredSize(new java.awt.Dimension(341, 24));
        P12.setRequestFocusEnabled(false);
        P12.setOpaque(true);
        P12.setPreferredSize(new java.awt.Dimension(341, 24));
        P12.setRequestFocusEnabled(false);


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(578, 578, 578)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton3)
                                    .addGap(18, 18, 18)
                                    .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addGap(18, 18, 18)
                                    .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton4)
                                    .addGap(18, 18, 18)
                                    .addComponent(P4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(P5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(P6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton8)
                                    .addGap(18, 18, 18)
                                    .addComponent(P8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton7)
                                    .addGap(18, 18, 18)
                                    .addComponent(P7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton10)
                                    .addGap(18, 18, 18)
                                    .addComponent(P10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton9)
                                    .addGap(18, 18, 18)
                                    .addComponent(P9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton11)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(P11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(73, 73, 73)
                                            .addComponent(P12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(607, 607, 607)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(850, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(P3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(P4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(P5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(P6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(P7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(P8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(P9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(P10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11)
                    .addComponent(P11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(P12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        MenuBar.setBounds(500, 0, 500, 50);
        MenuBar.setBackground(new java.awt.Color(85, 26, 139));
        MenuBar.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        MenuBar.setAlignmentX(-100.0F);
        MenuBar.setAutoscrolls(true);
        MenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuBar.setPreferredSize(new java.awt.Dimension(700, 80));

        MyAccountMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        MyAccountMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        MyAccountMenuItem.setText("MY ACCOUNT");
        MyAccountMenuItem.setOpaque(true);
        MyAccountMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        MyAccountMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyAccountMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyAccountMenuItemMouseExited(evt);
            }
        });
        MyAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyAccountMenuItemActionPerformed(evt);
            }
        });

        CartMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        CartMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        CartMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ShoppingCartM.png"))); // NOI18N
        CartMenuItem.setText("MY CART");
        CartMenuItem.setOpaque(true);
        CartMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartMenuItemMouseClicked(evt);
            }
  
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CartMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CartMenuItemMouseExited(evt);
            }
        });
        MyAccountMenuItem.add(CartMenuItem);

        AccountMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        AccountMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        AccountMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Account.png"))); // NOI18N
        AccountMenuItem.setText("MY ACCOUNT");
        AccountMenuItem.setFocusable(false);
        AccountMenuItem.setOpaque(true);
        AccountMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMenuItemMouseClicked(evt);
            }
        });
        AccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountMenuItemActionPerformed(evt);
            }
        });
        MyAccountMenuItem.add(AccountMenuItem);

        LogOutMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        LogOutMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        LogOutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        LogOutMenuItem.setText("LOG OUT");
        LogOutMenuItem.setOpaque(true);
        LogOutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMenuItemMouseClicked(evt);
            }
        });
        LogOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuItemActionPerformed(evt);
            }
        });
        MyAccountMenuItem.add(LogOutMenuItem);

        MenuBar.add(MyAccountMenuItem);

        MexicanMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        MexicanMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        MexicanMenuItem.setText("  MEXICAN KITCHEN");
        MexicanMenuItem.setOpaque(true);
        MexicanMenuItem.setPreferredSize(new java.awt.Dimension(120, 20));
        MexicanMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(MexicanMenuItem);

        GreekMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        GreekMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        GreekMenuItem.setText("GREEK KITCHEN");
        GreekMenuItem.setOpaque(true);
        GreekMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        GreekMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(GreekMenuItem);

        FrenchMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        FrenchMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        FrenchMenuItem.setText("FRENCH KITCHEN");
        FrenchMenuItem.setOpaque(true);
        FrenchMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        FrenchMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(FrenchMenuItem);

        ItalianMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        ItalianMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        ItalianMenuItem.setText("ITALIAN KITCHEN");
        ItalianMenuItem.setOpaque(true);
        ItalianMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        ItalianMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(ItalianMenuItem);

        HomeMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        HomeMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenuItem.setText("           HOME");
        HomeMenuItem.setOpaque(true);
        HomeMenuItem.setPreferredSize(new java.awt.Dimension(120, 20));
        HomeMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(HomeMenuItem);

        jMenu2.setBackground(new java.awt.Color(85, 26, 139));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Revenue.png"))); // NOI18N
        jMenu2.setOpaque(true);
        jMenu2.setPreferredSize(new java.awt.Dimension(700, 20));
        MenuBar.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(85, 26, 139));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jMenu1.setMaximumSize(new java.awt.Dimension(1100, 32767));
        jMenu1.setOpaque(true);
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 20));
        MenuBar.add(jMenu1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void CartMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMenuItemMouseEntered
        // TODO add your handling code here:
        AccountMenuItem.setBackground(new Color(255, 255, 255));
        AccountMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_CartMenuItemMouseEntered

    private void CartMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMenuItemMouseExited
        // TODO add your handling code here:
        AccountMenuItem.setBackground(new Color(85, 26, 139));
        AccountMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_CartMenuItemMouseExited

    private void AccountMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMenuItemMouseClicked
        // TODO add your handling code here:
    	new MyAccountPage().setVisible(true);
    	this.setVisible(false);
    	
    	
    }//GEN-LAST:event_AccountMenuItemMouseClicked

    private void AccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountMenuItemActionPerformed

    private void LogOutMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMenuItemMouseClicked
        // TODO add your handling code here:
        new LoginPageApp().setVisible(true);
        login.Login.putLoggedUserId(-1);
        login.Login.clearCart();
        this.setVisible(false);
    }//GEN-LAST:event_LogOutMenuItemMouseClicked

    private void LogOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutMenuItemActionPerformed

    private void MyAccountMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountMenuItemMouseEntered
        // TODO add your handling code here:
        MyAccountMenuItem.setBackground(new Color(255, 255, 255));
        MyAccountMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_MyAccountMenuItemMouseEntered

    private void MyAccountMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountMenuItemMouseExited
        // TODO add your handling code here:
        MyAccountMenuItem.setBackground(new Color(85, 26, 139));
        MyAccountMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_MyAccountMenuItemMouseExited

    private void MyAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyAccountMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyAccountMenuItemActionPerformed

    private void MexicanMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseClicked
        // TODO add your handling code here:
        new MexicanKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MexicanMenuItemMouseClicked

    private void MexicanMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseEntered
        // TODO add your handling code here:
        MexicanMenuItem.setBackground(new Color(255, 255, 255));
        MexicanMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_MexicanMenuItemMouseEntered

    private void MexicanMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseExited
        // TODO add your handling code here:
        MexicanMenuItem.setBackground(new Color(85, 26, 139));
        MexicanMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_MexicanMenuItemMouseExited

    private void GreekMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseClicked
        // TODO add your handling code here:
        new GreekKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GreekMenuItemMouseClicked

    private void GreekMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseEntered
        // TODO add your handling code here:
        GreekMenuItem.setBackground(new Color(255, 255, 255));
        GreekMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_GreekMenuItemMouseEntered

    private void GreekMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseExited
        // TODO add your handling code here:
        GreekMenuItem.setBackground(new Color(85, 26, 139));
        GreekMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_GreekMenuItemMouseExited

    private void FrenchMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseClicked
        // TODO add your handling code here:
        new FrenchKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FrenchMenuItemMouseClicked

    private void FrenchMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseEntered
        // TODO add your handling code here:
        FrenchMenuItem.setBackground(new Color(255, 255, 255));
        FrenchMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_FrenchMenuItemMouseEntered

    private void FrenchMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseExited
        // TODO add your handling code here:
        FrenchMenuItem.setBackground(new Color(85, 26, 139));
        FrenchMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_FrenchMenuItemMouseExited

    private void ItalianMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseClicked
        // TODO add your handling code here:
        new ItalianKitchenLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ItalianMenuItemMouseClicked

    private void ItalianMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseEntered
        // TODO add your handling code here:
        ItalianMenuItem.setBackground(new Color(255, 255, 255));
        ItalianMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_ItalianMenuItemMouseEntered

    private void ItalianMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseExited
        // TODO add your handling code here:
        ItalianMenuItem.setBackground(new Color(85, 26, 139));
        ItalianMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ItalianMenuItemMouseExited

    private void HomeMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseClicked
        // TODO add your handling code here:
        new HomePageLogged().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMenuItemMouseClicked

    private void HomeMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseEntered
        // TODO add your handling code here:
        HomeMenuItem.setBackground(new Color(255, 255, 255));
        HomeMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_HomeMenuItemMouseEntered

    private void HomeMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseExited
        // TODO add your handling code here:
        HomeMenuItem.setBackground(new Color(85, 26, 139));
        HomeMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_HomeMenuItemMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	login.Login.removeFromCart(0);
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    	
    	
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    	login.Login.removeFromCart(1);
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    	
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    	login.Login.removeFromCart(2);
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    	
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    	login.Login.removeFromCart(3);
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    	login.Login.removeFromCart(4);
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    	login.Login.removeFromCart(5);
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    	login.Login.removeFromCart(6);
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    	login.Login.removeFromCart(7);
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    	login.Login.removeFromCart(8);
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    	login.Login.removeFromCart(9);
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    	login.Login.removeFromCart(10);
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    	login.Login.clearCart();
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed
    
    private void CartMenuItemMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    	new MyCartPage().setVisible(true);
    	this.setVisible(false);
    }                                         

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCartPage().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AccountMenuItem;
    private javax.swing.JMenu CartMenuItem;
    private javax.swing.JMenu FrenchMenuItem;
    private javax.swing.JMenu GreekMenuItem;
    private javax.swing.JMenu HomeMenuItem;
    private javax.swing.JMenu ItalianMenuItem;
    private javax.swing.JMenu LogOutMenuItem;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MexicanMenuItem;
    private javax.swing.JMenu MyAccountMenuItem;
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P10;
    private javax.swing.JLabel P11;
    private javax.swing.JLabel P12;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P3;
    private javax.swing.JLabel P4;
    private javax.swing.JLabel P5;
    private javax.swing.JLabel P6;
    private javax.swing.JLabel P7;
    private javax.swing.JLabel P8;
    private javax.swing.JLabel P9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
