/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sabina
 */
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.event.MouseEvent;

import data.Encrypt;
import data.User;
public class RegisterPageApp extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPageApp
     */
    public RegisterPageApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CreateAccountLabel = new java.awt.Label();
        label1 = new java.awt.Label();
        EmailTextBox = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        PasswordTextBox = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        label3 = new java.awt.Label();
        NameTextBox = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        AddressTextBox = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        TelephoneTextBox = new javax.swing.JTextField();
        label6 = new java.awt.Label();
        AddressTextBox2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MyAccountMenuItem = new javax.swing.JMenu();
        SignUpMenuItem = new javax.swing.JMenu();
        LogInMenuItem = new javax.swing.JMenu();
        MexicanMenuItem = new javax.swing.JMenu();
        GreekMenuItem = new javax.swing.JMenu();
        FrenchMenuItem = new javax.swing.JMenu();
        ItalianMenuItem = new javax.swing.JMenu();
        HomeMenuItem = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(2100, 1200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/p1.jpg"))); // NOI18N

        CreateAccountLabel.setBackground(new java.awt.Color(255, 255, 255));
        CreateAccountLabel.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        CreateAccountLabel.setName("CreateAccountLabel"); // NOI18N
        CreateAccountLabel.setText("                     CREATE ACCOUNT");

        label1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        label1.setForeground(new java.awt.Color(85, 26, 139));
        label1.setText("Email");

        EmailTextBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EmailTextBox.setForeground(new java.awt.Color(122, 122, 122));
        EmailTextBox.setText("Fill in with your Email address");
        EmailTextBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 26, 139)));
        EmailTextBox.setCaretColor(new java.awt.Color(85, 26, 139));
        EmailTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmailTextBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmailTextBoxMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailTextBoxMouseClicked(evt);
            }
        });
        EmailTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextBoxActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        label2.setForeground(new java.awt.Color(85, 26, 139));
        label2.setText("Password");

        PasswordTextBox.setForeground(new java.awt.Color(122, 122, 122));
        PasswordTextBox.setText("Psssword");
        PasswordTextBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 26, 139)));
        PasswordTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordTextBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PasswordTextBoxMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordTextBoxMouseClicked(evt);
            }
        });

        SignUpButton.setBackground(new java.awt.Color(85, 26, 139));
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("Sign Up");
        SignUpButton.setToolTipText("Sign Up");
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(85, 26, 139));
        label3.setText("Name");

        NameTextBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        NameTextBox.setForeground(new java.awt.Color(122, 122, 122));
        NameTextBox.setText("Fill in with your Name");
        NameTextBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 26, 139)));
        NameTextBox.setCaretColor(new java.awt.Color(85, 26, 139));
        NameTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NameTextBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NameTextBoxMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameTextBoxMouseClicked(evt);
            }
        });
        NameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextBoxActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(85, 26, 139));
        label4.setText("Another Address");

        AddressTextBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AddressTextBox.setForeground(new java.awt.Color(122, 122, 122));
        AddressTextBox.setText("Fill in with your Address");
        AddressTextBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 26, 139)));
        AddressTextBox.setCaretColor(new java.awt.Color(85, 26, 139));
        AddressTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddressTextBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddressTextBoxMouseExited(evt);
            }
            
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddressTextBoxMouseClicked(evt);
            }
        });
        AddressTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextBoxActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(85, 26, 139));
        label5.setText("Telephone");

        TelephoneTextBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TelephoneTextBox.setForeground(new java.awt.Color(122, 122, 122));
        TelephoneTextBox.setText("Fill in with your Telephone number");
        TelephoneTextBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 26, 139)));
        TelephoneTextBox.setCaretColor(new java.awt.Color(85, 26, 139));
        TelephoneTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TelephoneTextBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TelephoneTextBoxMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TelephoneTextBoxMouseClicked(evt);
            }
        });
        TelephoneTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelephoneTextBoxActionPerformed(evt);
            }
        });

        label6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(85, 26, 139));
        label6.setText("Address");

        AddressTextBox2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AddressTextBox2.setForeground(new java.awt.Color(122, 122, 122));
        AddressTextBox2.setText("Fill in with another Address");
        AddressTextBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 26, 139)));
        AddressTextBox2.setCaretColor(new java.awt.Color(85, 26, 139));
        AddressTextBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddressTextBox2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddressTextBox2MouseExited(evt);
            }
            
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddressTextBox2MouseClicked(evt);
            }
        });
        AddressTextBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextBox2ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CreateAccountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(978, 978, 978)
                        .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(910, 910, 910)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailTextBox)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameTextBox)
                            .addComponent(PasswordTextBox)
                            .addComponent(TelephoneTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddressTextBox)
                            .addComponent(AddressTextBox2)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(937, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CreateAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PasswordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TelephoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddressTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddressTextBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(490, Short.MAX_VALUE))
        );

        MenuBar.setBounds(500, 0, 500, 50);
        MenuBar.setBackground(new java.awt.Color(85, 26, 139));
        MenuBar.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        MenuBar.setAlignmentX(-100.0F);
        MenuBar.setAutoscrolls(true);
        MenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuBar.setPreferredSize(new java.awt.Dimension(700, 80));

        MyAccountMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        MyAccountMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        MyAccountMenuItem.setText("MY ACCOUNT");
        MyAccountMenuItem.setOpaque(true);
        MyAccountMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        MyAccountMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyAccountMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyAccountMenuItemMouseExited(evt);
            }
        });

        SignUpMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        SignUpMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        SignUpMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Account.png"))); // NOI18N
        SignUpMenuItem.setText("Sign Up");
        SignUpMenuItem.setOpaque(true);
        SignUpMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpMenuItemMouseClicked(evt);
            }
        });
        MyAccountMenuItem.add(SignUpMenuItem);

        LogInMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        LogInMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        LogInMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        LogInMenuItem.setText("Log In");
        LogInMenuItem.setOpaque(true);
        LogInMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInMenuItemMouseClicked(evt);
            }
        });
        MyAccountMenuItem.add(LogInMenuItem);

        MenuBar.add(MyAccountMenuItem);

        MexicanMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        MexicanMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        MexicanMenuItem.setText(" MEXICAN KITCHEN");
        MexicanMenuItem.setOpaque(true);
        MexicanMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        MexicanMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MexicanMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(MexicanMenuItem);

        GreekMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        GreekMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        GreekMenuItem.setText("GREEK KITCHEN");
        GreekMenuItem.setOpaque(true);
        GreekMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        GreekMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GreekMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(GreekMenuItem);

        FrenchMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        FrenchMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        FrenchMenuItem.setText("FRENCH KITCHEN");
        FrenchMenuItem.setOpaque(true);
        FrenchMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        FrenchMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FrenchMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(FrenchMenuItem);

        ItalianMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        ItalianMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        ItalianMenuItem.setText("ITALIAN KITCHEN");
        ItalianMenuItem.setOpaque(true);
        ItalianMenuItem.setPreferredSize(new java.awt.Dimension(115, 20));
        ItalianMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ItalianMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(ItalianMenuItem);

        HomeMenuItem.setBackground(new java.awt.Color(85, 26, 139));
        HomeMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenuItem.setText("           HOME");
        HomeMenuItem.setOpaque(true);
        HomeMenuItem.setPreferredSize(new java.awt.Dimension(120, 20));
        HomeMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMenuItemMouseExited(evt);
            }
        });
        MenuBar.add(HomeMenuItem);

        jMenu2.setBackground(new java.awt.Color(85, 26, 139));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Revenue.png"))); // NOI18N
        jMenu2.setOpaque(true);
        jMenu2.setPreferredSize(new java.awt.Dimension(700, 20));
        MenuBar.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(85, 26, 139));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jMenu1.setMaximumSize(new java.awt.Dimension(1100, 32767));
        jMenu1.setOpaque(true);
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 20));
        MenuBar.add(jMenu1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void EmailTextBoxMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	
    	EmailTextBox.setText("");
	}

	protected void PasswordTextBoxMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	PasswordTextBox.setText("");		
	}

	protected void NameTextBoxMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	NameTextBox.setText("");		
	}

	protected void AddressTextBoxMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	AddressTextBox.setText("");			
	}

	protected void TelephoneTextBoxMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	TelephoneTextBox.setText("");				
	}

	protected void AddressTextBox2MouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	AddressTextBox2.setText("");				
	}

	private void MyAccountMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountMenuItemMouseEntered
        // TODO add your handling code here:
        MyAccountMenuItem.setBackground(new Color(255, 255, 255));
        MyAccountMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_MyAccountMenuItemMouseEntered

    private void MyAccountMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountMenuItemMouseExited
        // TODO add your handling code here:
        MyAccountMenuItem.setBackground(new Color(85, 26, 139));
        MyAccountMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_MyAccountMenuItemMouseExited

    private void MexicanMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseEntered
        // TODO add your handling code here:
        MexicanMenuItem.setBackground(new Color(255, 255, 255));
        MexicanMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_MexicanMenuItemMouseEntered

    private void MexicanMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseExited
        // TODO add your handling code here:
        MexicanMenuItem.setBackground(new Color(85, 26, 139));
        MexicanMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_MexicanMenuItemMouseExited

    private void GreekMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseEntered
        // TODO add your handling code here:
        GreekMenuItem.setBackground(new Color(255, 255, 255));
        GreekMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_GreekMenuItemMouseEntered

    private void GreekMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseExited
        // TODO add your handling code here:
        GreekMenuItem.setBackground(new Color(85, 26, 139));
        GreekMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_GreekMenuItemMouseExited

    private void FrenchMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseEntered
        // TODO add your handling code here:
        FrenchMenuItem.setBackground(new Color(255, 255, 255));
        FrenchMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_FrenchMenuItemMouseEntered

    private void FrenchMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseExited
        // TODO add your handling code here:
        FrenchMenuItem.setBackground(new Color(85, 26, 139));
        FrenchMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_FrenchMenuItemMouseExited

    private void ItalianMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseEntered
        // TODO add your handling code here:
        ItalianMenuItem.setBackground(new Color(255, 255, 255));
        ItalianMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_ItalianMenuItemMouseEntered

    private void ItalianMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseExited
        // TODO add your handling code here:
        ItalianMenuItem.setBackground(new Color(85, 26, 139));
        ItalianMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ItalianMenuItemMouseExited

    private void HomeMenuItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseEntered
        // TODO add your handling code here:
        HomeMenuItem.setBackground(new Color(255, 255, 255));
        HomeMenuItem.setForeground(new Color(85, 26, 139));
    }//GEN-LAST:event_HomeMenuItemMouseEntered

    private void HomeMenuItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseExited
        // TODO add your handling code here:
        HomeMenuItem.setBackground(new Color(85, 26, 139));
        HomeMenuItem.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_HomeMenuItemMouseExited

    private void EmailTextBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailTextBoxMouseEntered
        // TODO add your handling code here:

        EmailTextBox.setBackground(new Color(236, 223, 236));
    }//GEN-LAST:event_EmailTextBoxMouseEntered

    private void EmailTextBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailTextBoxMouseExited
        // TODO add your handling code here:
        EmailTextBox.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_EmailTextBoxMouseExited

    private void EmailTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextBoxActionPerformed

    private void PasswordTextBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTextBoxMouseEntered
        // TODO add your handling code here:
        PasswordTextBox.setBackground(new Color(236, 223, 236));
    }//GEN-LAST:event_PasswordTextBoxMouseEntered

    private void PasswordTextBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTextBoxMouseExited
        // TODO add your handling code here:
        PasswordTextBox.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_PasswordTextBoxMouseExited

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
        
    	String name = NameTextBox.getText();
    	String password = Encrypt.generateHash(new String(PasswordTextBox.getPassword()).toString());
    	System.out.println(new String(PasswordTextBox.getPassword()).toString());
    	System.out.println(password);
    	String email = EmailTextBox.getText();
		String telephone = TelephoneTextBox.getText();
		String address1 = AddressTextBox.getText();
		String address2 = AddressTextBox2.getText();

		if (!name.equals(null) && !name.equals("") && !name.equals("Fill in with your Name") && !email.equals(null) && !email.equals("") && !email.equals("Fill in with your Email address")
				&& !telephone.equals(null) && !telephone.equals("") && !telephone.equals("Fill in with your Telephone number") && !address1.equals(null) && !address1.equals("") && !address1.equals("Fill in with your Address")){
			User user = new User();
			user.setEmail(email);
			user.setName(name);
			user.setPassword(password);
			user.setTelephone(telephone);
			user.setAddress1(address1);
			if(!address2.equals("Fill in with another Address") && !address2.equals("") && !address2.equals(null))
			{
				user.setAddress2(address2);
			}
			else
			{
				user.setAddress2(null);
			}
			
			boolean response = servicii.web.AddUserServiceApp.postUser2(user);
			if(response == true)
		    {
				jLabel2.setVisible(false);
				new LoginPageApp().setVisible(true);
				this.setVisible(false);
		    }
			else
			{
				jLabel2.setText("This email already exists!");
		        jLabel2.setVisible(true);

			}
		}
		else
		{
			jLabel2.setText("All fields are mandatory!");
	        jLabel2.setVisible(true);
		}
		
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void NameTextBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameTextBoxMouseEntered
        // TODO add your handling code here:
        NameTextBox.setBackground(new Color(236, 223, 236));
    }//GEN-LAST:event_NameTextBoxMouseEntered

    private void NameTextBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameTextBoxMouseExited
        // TODO add your handling code here:
        NameTextBox.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_NameTextBoxMouseExited

    private void NameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextBoxActionPerformed

    private void AddressTextBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddressTextBoxMouseEntered
        // TODO add your handling code here:
        AddressTextBox.setBackground(new Color(236, 223, 236));
    }//GEN-LAST:event_AddressTextBoxMouseEntered

    private void AddressTextBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddressTextBoxMouseExited
        // TODO add your handling code here:
        AddressTextBox.setBackground(new Color(255, 255, 255));        
    }//GEN-LAST:event_AddressTextBoxMouseExited

    private void AddressTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextBoxActionPerformed

    private void TelephoneTextBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelephoneTextBoxMouseEntered
        // TODO add your handling code here:
        TelephoneTextBox.setBackground(new Color(236, 223, 236));              
    }//GEN-LAST:event_TelephoneTextBoxMouseEntered

    private void TelephoneTextBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelephoneTextBoxMouseExited
        // TODO add your handling code here:
        TelephoneTextBox.setBackground(new Color(255, 255, 255));        
    }//GEN-LAST:event_TelephoneTextBoxMouseExited

    private void TelephoneTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelephoneTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelephoneTextBoxActionPerformed

    private void AddressTextBox2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddressTextBox2MouseEntered
        // TODO add your handling code here:
        AddressTextBox2.setBackground(new Color(236, 223, 236));        
    }//GEN-LAST:event_AddressTextBox2MouseEntered

    private void AddressTextBox2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddressTextBox2MouseExited
        // TODO add your handling code here:
        AddressTextBox2.setBackground(new Color(255, 255, 255));        
    }//GEN-LAST:event_AddressTextBox2MouseExited

    private void AddressTextBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextBox2ActionPerformed

    private void HomeMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMenuItemMouseClicked
        // TODO add your handling code here:
        new HomePageApp().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeMenuItemMouseClicked

    private void SignUpMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMenuItemMouseClicked
        // TODO add your handling code here:
        new RegisterPageApp().setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_SignUpMenuItemMouseClicked

    private void LogInMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMenuItemMouseClicked
        // TODO add your handling code here:
        new LoginPageApp().setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_LogInMenuItemMouseClicked

    private void GreekMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreekMenuItemMouseClicked
        // TODO add your handling code here:
        new GreekKitchenApp().setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_GreekMenuItemMouseClicked

    private void MexicanMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanMenuItemMouseClicked
        // TODO add your handling code here:
        new MexicanKitchenApp().setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_MexicanMenuItemMouseClicked

    private void FrenchMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenchMenuItemMouseClicked
        // TODO add your handling code here:
        new FrenchKitchenApp().setVisible(true);
        this.setVisible(false);         
    }//GEN-LAST:event_FrenchMenuItemMouseClicked

    private void ItalianMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianMenuItemMouseClicked
        // TODO add your handling code here:
        new ItalianKitchenApp().setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_ItalianMenuItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPageApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextBox;
    private javax.swing.JTextField AddressTextBox2;
    private java.awt.Label CreateAccountLabel;
    private javax.swing.JTextField EmailTextBox;
    private javax.swing.JMenu FrenchMenuItem;
    private javax.swing.JMenu GreekMenuItem;
    private javax.swing.JMenu HomeMenuItem;
    private javax.swing.JMenu ItalianMenuItem;
    private javax.swing.JMenu LogInMenuItem;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MexicanMenuItem;
    private javax.swing.JMenu MyAccountMenuItem;
    private javax.swing.JTextField NameTextBox;
    private javax.swing.JPasswordField PasswordTextBox;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JMenu SignUpMenuItem;
    private javax.swing.JTextField TelephoneTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables
}
