/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-05-01 11:37:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class french_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Revenue</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/french.css\">\r\n");
      out.write("<link rel=\"icon\" href=\"images/logo.ico\" type=\"image/x-icon\">\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"loadKitchen('LoadFrench');\">\r\n");
      out.write("\t<!-- BARA DE NAVIGARE -->\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t\t<img src=\"images/logo.png\" alt=\"Logo\" id=\"icon\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/Revenue.png\" alt=\"Revenue\" id=\"icon2\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"\">French Kitchen <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mexic.jsp\"> &nbsp; Mexican Kitchen </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"italian.jsp\"> &nbsp; Italian Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"greek.jsp\"> &nbsp; Greek Kitchen </a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">Food <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#Appetizers\"> &nbsp; Appetizers </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#Soup\"> &nbsp; Soup </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#Salad\"> &nbsp; Salad </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#Entrees\"> &nbsp; Entrees </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#Dessert\"> &nbsp; Dessert </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#Drinks\"> &nbsp; Drinks </a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">My Account <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t");
 
								if(session.getAttribute("email") == null){
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"register.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></span> &nbsp; Sign Up </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"login.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> &nbsp; Log In</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 }
								else
							{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mycart.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-shopping-cart\" data-count=\"0\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp; My cart </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"myaccount.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-home\"></span> &nbsp; My account </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"logout.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\"></span> &nbsp; Log Out </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"myCarousel\" class=\"carousel slide col-lg-12 col-offset-2\">\r\n");
      out.write("\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t<img src=\"images/Coperta9.jpg\" alt=\"Plating\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h1>FRANCE - The city of love, fashion and art!</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container text-center\">\r\n");
      out.write("\t\t");

				if(session.getAttribute("name")!=null){
			
      out.write("\r\n");
      out.write("\t\t<h2\r\n");
      out.write("\t\t\tstyle=\"font-family: Montsserrat; font-style: italic; font-size: 2.3em;\">\r\n");
      out.write("\t\t\tBienvenue,\r\n");
      out.write("\t\t\t");

				String[] p = session.getAttribute("name").toString().split(" ");
				String nume="";
				for(int i=0;i<p.length;++i)
				{
					nume = nume + p[i].substring(0,1).toUpperCase() + p[i].substring(1).toLowerCase() + " ";
					//out.print(session.getAttribute("name").toString().substring(0,1).toUpperCase() + session.getAttribute("name").toString().substring(1).toLowerCase());			
				}
				out.print(nume);
				
      out.write("\r\n");
      out.write("\t\t\t! What do you want to eat today?\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t");
}
				else {
			
      out.write("\r\n");
      out.write("\t\t<h2\r\n");
      out.write("\t\t\tstyle=\"font-family: Montsserrat; font-style: italic; font-size: 2.3em;\">\r\n");
      out.write("\t\t\tBienvenue ! What do you want to eat today?</h2>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t<br /> <br />\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- APPETIZERS -->\r\n");
      out.write("\r\n");
      out.write("\t\t<h3\r\n");
      out.write("\t\t\tstyle=\"text-transform: uppercase; font-family: 'Montserrat'; font-style: italic;\"\r\n");
      out.write("\t\t\tid=\"Appetizers\">Appetizers</h3>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div id=\"Appetizers_div\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- SOUP -->\r\n");
      out.write("\t\t&nbsp;\r\n");
      out.write("\t\t<h3\r\n");
      out.write("\t\t\tstyle=\"text-transform: uppercase; font-family: 'Montserrat'; font-style: italic;\"\r\n");
      out.write("\t\t\tid=\"Soup\">Soup</h3>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div id=\"Soup_div\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- SALAD -->\r\n");
      out.write("\t\t&nbsp;\r\n");
      out.write("\t\t<h3\r\n");
      out.write("\t\t\tstyle=\"text-transform: uppercase; font-family: 'Montserrat'; font-style: italic;\"\r\n");
      out.write("\t\t\tid=\"Salad\">Salad</h3>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div id=\"Salad_div\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ENTREES -->\r\n");
      out.write("\t\t&nbsp;\r\n");
      out.write("\t\t<h3\r\n");
      out.write("\t\t\tstyle=\"text-transform: uppercase; font-family: 'Montserrat'; font-style: italic;\"\r\n");
      out.write("\t\t\tid=\"Entrees\">Entrees/Main dishes</h3>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div id=\"Entrees/MainDishes_div\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- DESSERT -->\r\n");
      out.write("\t\t&nbsp;\r\n");
      out.write("\t\t<h3\r\n");
      out.write("\t\t\tstyle=\"text-transform: uppercase; font-family: 'Montserrat'; font-style: italic;\"\r\n");
      out.write("\t\t\tid=\"Dessert\">Dessert</h3>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div id=\"Dessert_div\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- DRINKS -->\r\n");
      out.write("\t\t&nbsp;\r\n");
      out.write("\t\t<h3\r\n");
      out.write("\t\t\tstyle=\"text-transform: uppercase; font-family: 'Montserrat'; font-style: italic;\"\r\n");
      out.write("\t\t\tid=\"Drinks\">Drinks</h3>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div id=\"Drinks_div\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t");
 if( session.getAttribute("email") == null)
			{
			
			
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<style type = \"text/css\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t.btnAdd{\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</style>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			}
		else{
			session.setAttribute("page","french.jsp");
		}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"container-fluid text-center\">\r\n");
      out.write("\t\t<div>&copy; TI - PROIECT 2018</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
