/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-04-17 11:17:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Revenue</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/file.css\">\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"tabelXML('xml/table.xml')\">\r\n");
      out.write("\t<!-- BARA DE NAVIGARE -->\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t\t<img src=\"images/logo.png\" alt=\"Logo\" id=\"icon\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/Revenue.png\" alt=\"Revenue\" id=\"icon2\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Greek Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Mexican Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Italian Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">French Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"drodown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">My Account <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t");
 
						
						if(session.getAttribute("email") == null){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"register.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></span> &nbsp; Sign Up </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"login.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> &nbsp; Log In</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
						else
						{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-shopping-cart\"></span> &nbsp; My\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcart </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"myaccount.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-home\"></span> &nbsp; My account </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"logout.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\"></span> &nbsp; Log Out </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<!-- SLIDESHOW -->\r\n");
      out.write("\t<div id=\"myCarousel\" class=\"carousel slide col-lg-12 col-offset-2\">\r\n");
      out.write("\t\t<!-- INDICATORI -->\r\n");
      out.write("\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- COPERTA -->\r\n");
      out.write("\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t<img src=\"images/Coperta1.jpg\" alt=\"Plating\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h1>Welcome to Revenue!</h1>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<button onclick=\"location.href='register.jsp'\" name=\"button\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-default\">Create Account</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h1>Revenue Street Food!</h1>\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#table\" style=\"text-decoration: none; color: white;\">29\r\n");
      out.write("\t\t\t\t\t\t\tOctober 2019</a>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<img src=\"images/StreetFood.jpg\" alt=\"Street Food\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<img src=\"images/FourSeasonFourCountries.jpg\" alt=\"Four Countries\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h1>FOUR DIFFERENT COUNTRIES!</h1>\r\n");
      out.write("\t\t\t\t\t<h3>FOUR SEASON CUISINE</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- CONTROL STANGA-DREAPTA -->\r\n");
      out.write("\t\t\t<a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t\t<span class=\"glyphicon glyphicon-chevron-left\"></span> <span\r\n");
      out.write("\t\t\t\tclass=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t</a> <a class=\"right carousel-control\" href=\"#myCarousel\"\r\n");
      out.write("\t\t\t\tdata-slide=\"next\"> <span\r\n");
      out.write("\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></span> <span\r\n");
      out.write("\t\t\t\tclass=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- SPECIFIC GRECESC -->\r\n");
      out.write("\t<div class=\"container text-center\">\r\n");
      out.write("\t\t<h2\r\n");
      out.write("\t\t\tstyle=\"font-family: Montsserrat; font-style: italic; font-size: 2.3em;\">START\r\n");
      out.write("\t\t\tTHE DAY WITH US!</h2>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<img src=\"images/TraditionalGrecesc.jpg\" alt=\"Traditional Grecesc\"\r\n");
      out.write("\t\t\t\t\tclass=\"img-responsive\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<h4 style=\"text-transform: uppercase;\">Chicken Souvlaki with\r\n");
      out.write("\t\t\t\t\tPita Bread</h4>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<p>Souvlaki is one of the most popular street foods in Greece\r\n");
      out.write("\t\t\t\t\tand for good reason. It's stuffed with well cooked and seasoned\r\n");
      out.write("\t\t\t\t\tmeat, garnished with a cooling tzatziki sauce, wrapped in a\r\n");
      out.write("\t\t\t\t\tdelicious crispy pita and best of all? It tastes like heaven!\r\n");
      out.write("\t\t\t\t\tSouvlaki stands for \"meat-on-a-skewer\", however the majority of\r\n");
      out.write("\t\t\t\t\tGreeks and especially those from Athens call any type of pita\r\n");
      out.write("\t\t\t\t\twrapped meat a souvlaki, specifying the type of meat and method of\r\n");
      out.write("\t\t\t\t\troasting separately. For example Souvlaki with chicken Gyros or\r\n");
      out.write("\t\t\t\t\tSouvlaki with pork Skewers.</p>\r\n");
      out.write("\t\t\t\t<p>The most important step in making the perfect, traditional\r\n");
      out.write("\t\t\t\t\tGreek chicken souvlaki is nothing else but the marinade! For this\r\n");
      out.write("\t\t\t\t\ttraditional chicken souvlaki recipe, the chicken is first marinated\r\n");
      out.write("\t\t\t\t\tto soak up all the wonderful Mediterranean flavours and then\r\n");
      out.write("\t\t\t\t\tgrilled to high temperature, to get all crunchy, nicely coloured\r\n");
      out.write("\t\t\t\t\tand juicy. Select some good quality chicken breasts and season with\r\n");
      out.write("\t\t\t\t\ta selection of Greek spices like oregano, coat with extra virgin\r\n");
      out.write("\t\t\t\t\tolive oil and lemon juice and flavour with garlic. Marinading your\r\n");
      out.write("\t\t\t\t\tchicken souvlaki in the fridge for at least half an hour will allow\r\n");
      out.write("\t\t\t\t\tthe aromas to infuse the souvlaki and give it the desired flavours.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- SPECIFIC MEXICAN -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<h4 style=\"text-transform: uppercase;\">Chorizo and Avocado\r\n");
      out.write("\t\t\t\t\tBreakfast Tacos</h4>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<p>Tacos for breakfast? You bet!</p>\r\n");
      out.write("\t\t\t\t<p>Whether you have leftover chorizo from a previous meal, or\r\n");
      out.write("\t\t\t\t\tyou are just looking for a heartier way to jazz up your morning\r\n");
      out.write("\t\t\t\t\troutine, we can't think of a better way to start your day than to\r\n");
      out.write("\t\t\t\t\ttake this classic Tex-Mex meal from dinner to fuel-powered\r\n");
      out.write("\t\t\t\t\tbreakfast. It's as simple as adding eggs!</p>\r\n");
      out.write("\t\t\t\t<p>Perfect for a Cinco de Mayo celebration or a fun weekend\r\n");
      out.write("\t\t\t\t\tbrunch, you can transform the mundane breakfast of scrambled eggs\r\n");
      out.write("\t\t\t\t\twith a few simple and basic ingredients, such as avocados, onions,\r\n");
      out.write("\t\t\t\t\ttomatoes, and cheese. Have fun additions like tater tots, sour\r\n");
      out.write("\t\t\t\t\tcream, beans, salsa, hot sauce, bacon, and chives, and get your\r\n");
      out.write("\t\t\t\t\tkids engaged by creating a build-your-own-taco bar!</p>\r\n");
      out.write("\t\t\t\t<p>If you're ovo-vegetarian, you can leave out the chorizo (and\r\n");
      out.write("\t\t\t\t\tbacon).</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<img src=\"images/TraditionalMexican.jpg\" alt=\"Traditional Mexican\"\r\n");
      out.write("\t\t\t\t\tclass=\"img-responsive\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- SPECIFIC FRANCEZ -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<img src=\"images/Macarons.jpg\" alt=\"Macarons\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<h4 style=\"text-transform: uppercase;\">Macarons</h4>\r\n");
      out.write("\t\t\t\t<p>Macarons are the delicious sweet cookies filled with butter\r\n");
      out.write("\t\t\t\t\tcream. Macarons come in many colours so you can distinguish on the\r\n");
      out.write("\t\t\t\t\ttaste of the filling such as pink for raspberry taste, brown for\r\n");
      out.write("\t\t\t\t\tchocolate, yellow for vanilla or lemon, green for pistachio, blue\r\n");
      out.write("\t\t\t\t\tfor ...blueberry... and mmmh, the French macaroons melt in the\r\n");
      out.write("\t\t\t\t\tmouth!</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- SPECIFIC ITALIAN -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<img src=\"images/TraditionalItalian.jpg\" alt=\"Traditional Italian\"\r\n");
      out.write("\t\t\t\t\tclass=\"img-responsive\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<h4 style=\"text-transform: uppercase;\">Italian Beef</h4>\r\n");
      out.write("\t\t\t\t<p>This is a favorite Italian beef recipe , made with a pot\r\n");
      out.write("\t\t\t\t\troast and Italian salad dressing. The pepperoncini adds extra\r\n");
      out.write("\t\t\t\t\tflavor to the meat.</p>\r\n");
      out.write("\t\t\t\t<p>Thicken the liquids to make a sauce for the beef or serve the\r\n");
      out.write("\t\t\t\t\tshredded beef with some of the juices and prepared brown gravy.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- TABELA XML CU DATELE ORGANIZATORICE PENTRU STREET FOOD -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\" id=\"continut\">\r\n");
      out.write("\t\t\t\t<h4 style=\"text-transform: uppercase;\">\r\n");
      out.write("\t\t\t\t\t<a id=\"table\" style=\"color: black;\"> Where can you find us ? </a>\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t<table id=\"tabel\">\r\n");
      out.write("\t\t\t\t\t<tr style=\"background-color: #551A8B;\">\r\n");
      out.write("\t\t\t\t\t\t<th>CITY</th>\r\n");
      out.write("\t\t\t\t\t\t<th>DATE</th>\r\n");
      out.write("\t\t\t\t\t\t<th>LOCATION</th>\r\n");
      out.write("\t\t\t\t\t\t<th>HOUR</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<img src=\"images/StreetFood1.jpg\" alt=\"Street Food Revenue\"\r\n");
      out.write("\t\t\t\t\tclass=\"img-responsive\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- FOOTER TI PROIECT 2018 -->\r\n");
      out.write("\t<footer class=\"container-fluid text-center\">\r\n");
      out.write("\t\t<div>&copy; TI - PROIECT 2018</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
