/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-05-01 13:33:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.Cart;

public final class myaccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.Cart");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Revenue</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/file.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"icon\" href=\"images/logo.ico\" type=\"image/x-icon\">\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- BARA DE NAVIGARE -->\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t\t<img src=\"images/logo.png\" alt=\"Logo\" id=\"icon\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/Revenue.png\" alt=\"Revenue\" id=\"icon2\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"greek.jsp\">Greek Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mexic.jsp\">Mexican Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"italian.jsp\">Italian Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"french.jsp\">French Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"drodown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">My Account <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								if (session.getAttribute("email") == null) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"register.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></span> &nbsp; Sign Up </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"login.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> &nbsp; Log In</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mycart.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-shopping-cart\" data-count=\"\r\n");
Cart cart = (Cart) session.getAttribute("cart");
											if(cart != null){
												int y=0;
												int x = cart.getOrder().size();
												for(int i=0;i<x;++i){
													y+=cart.getOrder().get(i).getQuantity();
												}
												out.println(y);
												}
      out.write("\"></span> &nbsp; My\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcart </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"myaccount.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-home\"></span> &nbsp; My account </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"logout.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\"></span> &nbsp; Log Out </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container text-center\">\r\n");
      out.write("\t\t");

			if (session.getAttribute("email") != null) {
		
      out.write("\r\n");
      out.write("\t\t<h2\r\n");
      out.write("\t\t\tstyle=\"font-family: Montsserrat; font-style: italic; font-size: 2.3em;\">THANK\r\n");
      out.write("\t\t\tYOU FOR BEING OUR CLIENT!</h2>\r\n");
      out.write("\t\t<br /> <br />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<h4\r\n");
      out.write("\t\t\tstyle=\"text-align: center; font-family: Montsserrat; font-style: italic; font-size: 1.6em\">PLEASE\r\n");
      out.write("\t\t\tCHECK YOUR DATA!</h4>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"align1 alignLeft12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<label class=\"align1\" for=\"VEmail\">Email</label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" name=\"VEmail\" id=\"VEmail\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=");
out.println(session.getAttribute("email").toString());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\treadonly>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<br /> <label class=\"align1\" for=\"VName\">Name</label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"VName\" id=\"VName\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=");
out.println(session.getAttribute("name").toString());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\treadonly>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<br /> <label class=\"align1\" for=\"VTelephone\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-left: 55%\">Telephone</label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input style=\"margin-left: 55%\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"VTelephone\" id=\"VTelephone\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
System.out.println(session.getAttribute("telephone"));
							if (session.getAttribute("telephone") != null){
								out.println(session.getAttribute("telephone").toString());}
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\treadonly>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"align1 alignRight12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<label class=\"align1\" for=\"VAddress\">First Address</label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"VAddress\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"VAddress\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
if (session.getAttribute("address1") != null){
								out.println(session.getAttribute("address1").toString());}
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\treadonly>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<br /> <label class=\"align1\" for=\"VAddress2\">Second\r\n");
      out.write("\t\t\t\t\t\tAddress</label>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"VAddress2\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"VAddress2\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
if (session.getAttribute("address2") != null){
								out.println(session.getAttribute("address2").toString());}
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\treadonly>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");

			} else {
		
      out.write("\r\n");
      out.write("\t\t<!-- ERROR MESSAGE -->\r\n");
      out.write("\t\t<span id=\"mesaj\"> ");

 	out.println("You are not logged in!");
 
      out.write("\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<img src=\"images/Restaurant.jpg\" class=\"img-responsive\"\r\n");
      out.write("\t\t\t\t\talt=\"Restaurant\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<h4 style=\"text-transform: uppercase;\">CONTACT</h4>\r\n");
      out.write("\t\t\t\t<p style=\"float: left\">If you have a problem with the food, our\r\n");
      out.write("\t\t\t\t\tservices,delivery guys, please contact us at the following\r\n");
      out.write("\t\t\t\t\taddresses and phone numbers:</p>\r\n");
      out.write("\t\t\t\t<p>&#9674; Street Restaurant | 3407 Greystone Drive | Austin MX\r\n");
      out.write("\t\t\t\t\t78731 | (511) 311-9111</p>\r\n");
      out.write("\t\t\t\t<p>&#9674; (156) 121-7181</p>\r\n");
      out.write("\t\t\t\t<p>&#9674; (267) 128-7182</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<img src=\"images/Facebook.jpg\" class=\"img-responsive\" alt=\"Facebook\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<h4 style=\"text-transform: uppercase;\">Visit Us</h4>\r\n");
      out.write("\t\t\t\t<p>Contact us on Facebook and Instagram !</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<img src=\"images/FacebookLogo.png\" class=\"img-responsive\"\r\n");
      out.write("\t\t\t\t\talt=\"Facebook\" width=\"150\"> <a href=\"#\">www.facebook.com/revenue5</a>\r\n");
      out.write("\t\t\t\t<br /> <br />\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<img src=\"images/InstagramLogo.png\" class=\"img-responsive\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Instagram\" width=\"150\"> <a href=\"#\">www.instagram.com/revenue5</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"container-fluid text-center\">\r\n");
      out.write("\t\t<div>&copy; TI - PROIECT 2018</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
