/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.29
 * Generated at: 2018-05-01 12:56:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.Cart;

public final class mycart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.Cart");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Revenue</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.2.4.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/file.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"icon\" href=\"images/logo.ico\" type=\"image/x-icon\">\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- BARA DE NAVIGARE -->\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t\t<img src=\"images/logo.png\" alt=\"Logo\" id=\"icon\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/Revenue.png\" alt=\"Revenue\" id=\"icon2\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"greek.jsp\">Greek Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mexic.jsp\">Mexican Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"italian.jsp\">Italian Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"french.jsp\">French Kitchen</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"drodown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">My Account <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t");
 
						
						if(session.getAttribute("email") == null){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"register.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></span> &nbsp; Sign Up </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"login.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> &nbsp; Log In</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
						else
						{
							session.setAttribute("page", "mycart.jsp");
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mycart.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-shopping-cart\" data-count=\"0\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp; My cart </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"myaccount.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-home\"></span> &nbsp; My account </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"logout.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\"></span> &nbsp; Log Out </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container text-center\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"shopping-cart\">\r\n");
      out.write("\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t<h2\r\n");
      out.write("\t\t\t\t\tstyle=\"font-family: Montsserrat; font-style: italic; font-size: 2.3em;\">SHOPPING\r\n");
      out.write("\t\t\t\t\tCART</h2>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					
					Cart cart = (Cart) session.getAttribute("cart");
				if(cart != null){
					int x = cart.getOrder().size();
					for(int i=0;i<x;++i){
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Product -->\r\n");
      out.write("\t\t\t\t<div class=\"items\">\r\n");
      out.write("\t\t\t\t\t<div class=\"buttons\">\r\n");
      out.write("\t\t\t\t\t<form action=\"/RemoveClass\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"Remove\" value=\"");
 out.print(cart.getOrder().get(i).getProduct().getName()); 
      out.write("\" style=\"background:white; color:black; border:none;\">\r\n");
      out.write("\t\t\t\t\t      <span class=\"glyphicon glyphicon-remove\" style=\"color:#551A8B\"></span>\r\n");
      out.write("\t\t\t\t\t    </button> \r\n");
      out.write("\t\t\t\t\t    </form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"image\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
out.print(cart.getOrder().get(i).getProduct().getImg()); 
      out.write("\" alt=\"\" /> <!-- TREBUIE LUATA SI IMAGINEA DIN BAZA DE DATE --> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"description\">\r\n");
      out.write("\t\t\t\t\t\t<span>");
 out.print(cart.getOrder().get(i).getProduct().getName()); 
      out.write("</span> <span>");
 out.print(cart.getOrder().get(i).getProduct().getKitchen()); 
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"quantity\">\r\n");
      out.write("\t\t\t\t\t<form action=\"/PlusClass\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"plus-btn\" name=\"Plus\" value=\"");
 out.print(cart.getOrder().get(i).getProduct().getName()); 
      out.write("\" type=\"submit\" >\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-plus\" style=\"color:#551A8B\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id = \"");
out.print(cart.getOrder().get(i).getProduct().getName()); 
      out.write("\"name=\"name\" value=\"");
 out.print(cart.getOrder().get(i).getQuantity());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<form action=\"/MinusClass\" method=\"POST\">\t\r\n");
      out.write("\t\t\t\t\t\t<button class=\"minus-btn\" name=\"Minus\" value=\"");
 out.print(cart.getOrder().get(i).getProduct().getName()); 
      out.write("\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-minus\" style=\"color:#551A8B\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"total-price\">");
 out.print(cart.getOrder().get(i).getProduct().getPrice()); 
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<p style=\"text-align:right; font-size:16px; font-family:Montserrat; font-style:italic;\">\r\n");
      out.write("\t\t\t\t\tTOTAL : ");
 out.print(cart.getTotalPrice());
      out.write(" &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<h2\r\n");
      out.write("\t\t\t\t\tstyle=\"font-family: Montsserrat; font-style: italic; font-size: 1.6em;\">YOUR SHOPPING\r\n");
      out.write("\t\t\t\t\tCART IS EMPTY!</h2>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- FOOTER TI PROIECT 2018 -->\r\n");
      out.write("\t<footer class=\"container-fluid text-center\">\r\n");
      out.write("\t\t<div>&copy; TI - PROIECT 2018</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
